name: Scheduled test

on:
  schedule:
    - cron: "0 0 * * WED"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run test
        run: go test -v ./...
